version: "3"
services:
  backend:
    image: mypos-backend:1.0
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://patcharapn:1234@cluster0.3tswjdg.mongodb.net/myPOS
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
